### ISSUE TITLE
on all versions endpoint show version as number (and hide the `v` prefix)

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/ctibutler#27]
should be

```
[
  {
    "modified": "2022-05-11T14:00:00.188Z",
    "versions": [
      "1",
      "2",
      "3"
    ]
```

**Comment by himynamesdave** [comment]
All version endpoints (framework/objects) now returning empty response

e.g.

curl -X 'GET' \
  'http://127.0.0.1:8006/api/v1/attack-enterprise/versions/' \
  -H 'accept: application/json'

{
  "latest": null,
  "versions": []
}


curl -X 'GET' \
  'http://127.0.0.1:8006/api/v1/attack-enterprise/objects/T1499.004/versions/' \
  -H 'accept: application/json'

[]

**Comment by himynamesdave** [comment]
@fqrious rebuilt and still see this. Have you changed how objects are imported?

**Comment by fqrious** [comment]
yes

**Comment by fqrious** [comment]
I upload with `_stix2arango_note` = `version={version}` not `v{version}`.
