### ISSUE TITLE
Location versions endpoint returning no results, despite versions existing

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/ctibutler#33]
```
curl -X 'GET' \
  'http://127.0.0.1:8006/api/v1/location/versions/' \
  -H 'accept: application/json'
```

```
{
  "latest": null,
  "versions": []
}
```

I think this is because version of locations is not a number, but a string

**Comment by fqrious** [comment]
did you upload the objects through ctibutler? if not it's probably because your method doesn't use `version={version_without_v}` in `s2a_note`. This works on my side
