### ISSUE TITLE
Remove SCO / SDO / SRO id object endpoints

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/ctibutler#9]
There is no need to split these out like

/api/v1/objects/sdos/{object_id}/
/api/v1/objects/scos/{object_id}/
etc

should just have one endpoint 

/api/v1/objects/{object_id}/

The search endpoints

e.g. 

/api/v1/objects/scos/

should remain, to allow a user to find an object type

**Comment by fqrious** [comment]
I was asked to do this before, https://github.com/muchdogesec/obstracts/issues/73
